[package]
name = "nesso"
version = "0.1.0"
edition = "2024"
default-run = "nesso"

[dependencies]
axum = "0.8.9"
base64 = "0.23.1"
crc32fast = "1.5.1"
getset = "0.1.7"
hdrhistogram = "7.6.0"
rand = "0.10.2"
reqwest = { version = "0.13.4", features = ["json"] }
rusqlite = { version = "0.40.2", features = ["bundled"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
statrs = "0.19.1"
tokio = { version = "1.53.1", features = ["full"] }
tokio-util = "0.7.19"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"

[profile.bench]
opt-level = 3
lto = "thin"
codegen-units = 1

